# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af104654ff946a4e9ac5c3bc77fbf593d9e091a19f4a33f712ac5d2f2adf24ff45cb33dd184b0751d3505d7b7cfa2ff39e154e83b99135528ae46fb1c9f1696a

test:
  secret_key_base: 5853a4084d818edb3605eafc36833405f255408dda18eec5d39968ca251f4fabc6c063a0b05c7111b83f12e7de20c8e6d2c5e5aa8f9c7b5a5a2d7650c63ec306

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
